// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CharacterSelectController from "./character_select_controller"
application.register("character-select", CharacterSelectController)

import ConversationController from "./conversation_controller"
application.register("conversation", ConversationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageController from "./message_controller"
application.register("message", MessageController)
