app = "llmrpg"

primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "bluegreen"

[env]
  HTTP_PORT = 8080
  SOLID_QUEUE_IN_PUMA = true

[processes]
  web = "./bin/thrust ./bin/rails server"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/up"
